### ISSUE TITLE
Formatting errors with gulp-util

### ISSUE THREAD

**Issue by rhys-vdw** [contra/gulp-coffee#61] opened 2015-04-21 00:59 UTC
I'm having trouble getting nicely formatted errors. Following the example, I have the following:

``` JavaScript
// Compile coffee into temp folder, unconcatenated and uniminified.
gulp.task('scripts', function (done) {
  return gulp.src(appSrc.scripts)
    .pipe(plumber())
    .pipe(coffee({bare: false}).on('error', util.log))
    .pipe(ngAnnotate())
    .pipe(gulp.dest(compileDest.scripts))
    .pipe(size())
    ;
});
```

But I get output that looks like this:

```
[10:53:53] { [SyntaxError: unexpected newline]
  location:
   { first_line: 849,
     first_column: 51,
     last_line: 849,
     last_column: 51 },
  toString: [Function],
  code: '\n# Not a good thing\nhandleError = (debug, task) -> (error) ->\n  debug.error \'Error\', error\n  alert "An error occured while performing #{ task }"\n\nangular.module \'hummingbirdControllers\', [\'hummingbirdConstants\', \'ngAnimate\']\n\n.controller \'LoginCtrl\' [CODE REDACTED...]',
  filename: '/Users/rhysvanderwaerden/Projects/hummingbird/hummingbird-frontend/app/scripts/controllers.coffee',
  name: 'SyntaxError',
  message: 'unexpected newline',
  stack: '/Users/rhysvanderwaerden/Projects/hummingbird/hummingbird-frontend/app/scripts/controllers.coffee:850:52: error: unexpected newline\n     "#{ invitationsRoute }/:invitationId": [\'GET\']\u001b[1;31m\u001b[0m\n\u001b[1;31m                                                   ^\u001b[0m',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-coffee' }
```

How can I get this to be formatted and readable? I've updated gutil, gulp and gulp-coffee to the newest versions...

**Comment by contra** [comment] 2015-04-21 14:35
How does `.on('error', console.error))` look?

**Comment by rhys-vdw** [comment] 2015-04-21 22:46
Same output with console.error.

Okay, so this prints correctly:

```JavaScript
gulp.task('scripts', function (done) {
  return gulp.src(appSrc.scripts)
    .pipe(coffee())
    .on('error', util.log)
    .pipe(gulp.dest(compileDest.scripts))
    .pipe(size())
    ;
});
```

And both of these print output as above:

```JavaScript
gulp.task('scripts', function (done) {
  return gulp.src(appSrc.scripts)
    .pipe(coffee())
    .on('error', util.log)
    .pipe(gulp.dest(compileDest.scripts))
    .pipe(size())
    ;
});
```

```JavaScript
gulp.task('scripts', function (done) {
  return gulp.src(appSrc.scripts)
    .pipe(coffee().on('error', util.log))
    .pipe(gulp.dest(compileDest.scripts))
    .pipe(size())
    ;
});
```

**Comment by contra** [comment] 2015-04-22 00:03
Different versions of gulp-util? Are you sure everything is up to date with the latest?

**Comment by edmundito** [comment] 2015-10-16 03:35
I peeked into gulp-util (3.0.6) myself and found that for whatever reason, the error is not being formatted `toString()`. This is is how I worked around it in my gulpfile:

```coffeescript
$ = require('gulp-load-plugins')()
errorHandler = (error) -> $.util.log error.toString()

# Inside the task...
.pipe($.coffee(bare: true).on('error', errorHandler))
```

**Comment by contra** [comment] 2015-10-16 04:59
@edmundito Something that needs to be fixed in gulp-util? What were your findings?

**Comment by edmundito** [comment] 2015-10-16 05:35
Yes, this is mainly related to the implementation of the `log()` function in gulp-util 3.0.6. I've noticed that master is currently a bit different, however what I found is that it has to do with the behavior of `console.log` in Node (as well as Chrome and Safari). `console.log` seems to not respect the `toString` declaration when outputting objects by themselves:

```
$ node
> function Cls() {}; Cls.prototype.toString = function () { return 'the string'; }
[Function]
> var c = new Cls()
undefined
> console.log(c)
Cls {}
undefined
> console.log(c.toString())
the string
undefined
> console.log('' + c)
the string
undefined
> console.log.apply(console, [c, c, c])
Cls {} Cls {} Cls {}
```

This could also be the cause behind the result in gulpjs/gulp-util#74.

**Comment by contra** [comment] 2015-10-16 20:39
The PluginError class is a disaster in gulp-util right now - there are plans to replace it with something simpler called BetterError but I haven't had time to dedicate to it.

With that - I'd take a PR to fix this issue in gulp-util if any of you have time.

**Comment by contra** [comment] 2017-12-31 17:58
Closing, this was split out of gulp-util into the `plugin-error` module and we use that now. Any fixes for formatting should go there.

**Closed by contra** 2017-12-31 17:58 UTC
